sonar.projectKey=test-azure-cicd
sonar.organization=your-org-name

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=TestAzureCICD
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app
sonar.exclusions=**/*.xml,**/*.yml,**/tests/**,**/venv/**,.github/**,Dockerfile

# Testing and coverage configuration
sonar.tests=app
sonar.test.inclusions=test_*.py
sonar.python.coverage.reportPaths=coverage.xml
