name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry (or Docker Hub)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/fastapi-app:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/fastapi-app:${{ github.sha }}

    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/fastapi-app:${{ github.sha }}'
